import { PrintDocType, PrintDocConfig, StoreSettings } from '../types';

export const DEFAULT_DOC_TEMPLATES: Record<
  PrintDocType,
  {
    title: string;
    subtitle?: string;
    notes: string[];
    signLeft: string;
    signRight: string;
    defaultSize: 'A4' | 'A5' | 'K80' | 'K58';
    defaultOrientation: 'portrait' | 'landscape';
    defaultEmptyRows: number;
    signatureStyle: 'two_blocks' | 'five_blocks';
    showVietQR: boolean;
    showBarcode: boolean;
    showDocQr: boolean;
    showBankInfo: boolean;
    showLogo: boolean;
    codePlacement: 'header' | 'footer' | 'both';
  }
> = {
  sales_invoice: {
    title: 'HÓA ĐƠN BÁN HÀNG',
    subtitle: '',
    notes: [
      '1. Giá trên bao gồm VAT 8%. Chưa bao gồm phí vận chuyển và cấu hình lắp đặt ( Liên hệ: 0914 665 994 Mr. Thơm)',
      '2. Bảo hành 1 năm theo tiêu chuẩn nhà sản xuất tại Công Ty Gia Phúc',
      '3. Hình thức thanh toán: Tiền mặt/ chuyển khoản',
      '4. Vui lòng kiểm tra hàng trước khi rời khỏi công ty',
    ],
    signLeft: 'Khách hàng / Người nhận',
    signRight: 'Người lập hóa đơn',
    defaultSize: 'A4',
    defaultOrientation: 'portrait',
    defaultEmptyRows: 4,
    signatureStyle: 'two_blocks',
    showVietQR: true,
    showBarcode: true,
    showDocQr: true,
    showBankInfo: true,
    showLogo: true,
    codePlacement: 'header',
  },
  sales_order: {
    title: 'ĐƠN ĐẶT HÀNG',
    subtitle: '',
    notes: [
      '1. Giá trên bao gồm VAT 8%. Chưa bao gồm phí vận chuyển và cấu hình lắp đặt ( Liên hệ: 0914 665 994 Mr. Thơm)',
      '2. Bảo hành 1 năm theo tiêu chuẩn nhà sản xuất tại Công Ty Gia Phúc',
      '3. Hình thức thanh toán: Thanh toán 50% Tiền mặt/ chuyển khoản sau khi đặt hàng',
      '4. Vui lòng kiểm tra hàng trước khi rời khỏi công ty',
    ],
    signLeft: 'Đại diện bên mua (Khách hàng)',
    signRight: 'Đại diện bên bán',
    defaultSize: 'A4',
    defaultOrientation: 'portrait',
    defaultEmptyRows: 4,
    signatureStyle: 'two_blocks',
    showVietQR: true,
    showBarcode: true,
    showDocQr: true,
    showBankInfo: true,
    showLogo: true,
    codePlacement: 'header',
  },
  goods_receipt: {
    title: 'PHIẾU NHẬP KHO',
    subtitle: '',
    notes: [
      '1. Hàng hóa nhập kho mới 100%, nguyên đai nguyên kiện, đúng quy cách theo đơn đặt hàng',
      '2. Thủ kho và bên giao đã kiểm đếm đầy đủ số lượng và xác nhận tình trạng',
      '3. Chứng từ gốc kèm theo: Hóa đơn / Phiếu giao hàng của nhà cung cấp',
    ],
    signLeft: 'Người giao hàng (Nhà cung cấp)',
    signRight: 'Thủ kho tiếp nhận',
    defaultSize: 'A4',
    defaultOrientation: 'portrait',
    defaultEmptyRows: 4,
    signatureStyle: 'two_blocks',
    showVietQR: false,
    showBarcode: true,
    showDocQr: true,
    showBankInfo: false,
    showLogo: true,
    codePlacement: 'header',
  },
  exchange_return: {
    title: 'PHIẾU ĐỔI TRẢ HÀNG HÓA KIÊM PHIẾU NHẬP XUẤT',
    subtitle: '',
    notes: [
      '1. Sản phẩm đổi trả phải còn nguyên tem bảo hành, phụ kiện đầy đủ, không trầy xước cấn móp',
      '2. Áp dụng theo chính sách đổi trả trong vòng 7 ngày kể từ ngày mua hàng',
      '3. Số tiền hoàn lại (nếu có) được chi trả bằng tiền mặt hoặc cấn trừ công nợ',
    ],
    signLeft: 'Khách hàng yêu cầu đổi trả',
    signRight: 'Người tiếp nhận xử lý',
    defaultSize: 'A4',
    defaultOrientation: 'portrait',
    defaultEmptyRows: 3,
    signatureStyle: 'two_blocks',
    showVietQR: true,
    showBarcode: true,
    showDocQr: true,
    showBankInfo: true,
    showLogo: true,
    codePlacement: 'header',
  },
  warranty_intake: {
    title: 'PHIẾU NHẬN HÀNG BẢO HÀNH',
    subtitle: '',
    notes: [
      '1. Thiết bị tiếp nhận phải còn tem niêm phong bảo hành của Gia Phúc Computer hoặc nhà sản xuất',
      '2. Không bảo hành các trường hợp: Rơi vỡ, vô nước, cháy nổ chip/IC, côn trùng xâm nhập',
      '3. Thời gian xử lý kiểm tra bảo hành: từ 03 đến 07 ngày làm việc (không tính CN & ngày lễ)',
      '4. Quý khách vui lòng giữ phiếu này để đối chiếu khi nhận lại thiết bị',
    ],
    signLeft: 'Khách hàng gửi máy',
    signRight: 'Kỹ thuật viên tiếp nhận',
    defaultSize: 'A5',
    defaultOrientation: 'portrait',
    defaultEmptyRows: 2,
    signatureStyle: 'two_blocks',
    showVietQR: false,
    showBarcode: true,
    showDocQr: true,
    showBankInfo: false,
    showLogo: true,
    codePlacement: 'header',
  },
  warranty_return: {
    title: 'PHIẾU TRẢ HÀNG BẢO HÀNH',
    subtitle: '',
    notes: [
      '1. Thiết bị đã được kiểm tra kỹ thuật hoạt động ổn định và dán tem bảo hành bổ sung',
      '2. Khách hàng vui lòng kiểm tra lại thiết bị và phụ kiện trước khi rời quầy',
      '3. Mọi khiếu nại về ngoại quan sau khi nhận máy sẽ không được giải quyết',
    ],
    signLeft: 'Khách hàng nhận lại thiết bị',
    signRight: 'Kỹ thuật viên bàn giao',
    defaultSize: 'A5',
    defaultOrientation: 'portrait',
    defaultEmptyRows: 2,
    signatureStyle: 'two_blocks',
    showVietQR: false,
    showBarcode: true,
    showDocQr: true,
    showBankInfo: false,
    showLogo: true,
    codePlacement: 'header',
  },
  delivery_note: {
    title: 'PHIẾU XUẤT KHO KIÊM GIAO HÀNG',
    subtitle: '',
    notes: [
      '1. Hàng hóa xuất kho đúng chủng loại, số lượng và tiêu chuẩn chất lượng',
      '2. Người nhận kiểm tra kỹ hàng hóa và tem niêm phong trước khi ký nhận',
      '3. Phiếu lập thành 02 liên: Liên 1 lưu tại kho, Liên 2 giao cho người nhận',
    ],
    signLeft: 'Người nhận hàng',
    signRight: 'Thủ kho xuất hàng',
    defaultSize: 'A5',
    defaultOrientation: 'portrait',
    defaultEmptyRows: 2,
    signatureStyle: 'two_blocks',
    showVietQR: true,
    showBarcode: true,
    showDocQr: true,
    showBankInfo: true,
    showLogo: true,
    codePlacement: 'header',
  },
  warranty_receipt: {
    title: 'PHIẾU BÁN HÀNG & BẢO HÀNH THIẾT BỊ',
    subtitle: '',
    notes: [
      '1. Hàng hóa chính hãng được bảo hành theo số Serial/IMEI dán trên thiết bị',
      '2. Thời gian bảo hành được tính từ ngày lập phiếu',
      '3. Vui lòng giữ phiếu hoặc bảo quản tem bảo hành để được hỗ trợ tốt nhất',
    ],
    signLeft: 'Khách hàng',
    signRight: 'Nhân viên bán hàng',
    defaultSize: 'A4',
    defaultOrientation: 'portrait',
    defaultEmptyRows: 4,
    signatureStyle: 'two_blocks',
    showVietQR: true,
    showBarcode: true,
    showDocQr: true,
    showBankInfo: true,
    showLogo: true,
    codePlacement: 'header',
  },
  payment_receipt: {
    title: 'PHIẾU THU TIỀN',
    subtitle: '',
    notes: [
      '1. Phiếu thu chỉ có giá trị khi có đầy đủ chữ ký của người nộp và thủ quỹ',
      '2. Đề nghị Quý khách kiểm tra số tiền trước khi rời khỏi quầy giao dịch',
    ],
    signLeft: 'Người nộp tiền',
    signRight: 'Thủ quỹ / Người lập phiếu',
    defaultSize: 'A5',
    defaultOrientation: 'portrait',
    defaultEmptyRows: 2,
    signatureStyle: 'two_blocks',
    showVietQR: true,
    showBarcode: true,
    showDocQr: true,
    showBankInfo: true,
    showLogo: true,
    codePlacement: 'header',
  },
  einvoice_vat: {
    title: 'HÓA ĐƠN GIÁ TRỊ GIA TĂNG',
    subtitle: '(Bản thể hiện của hóa đơn điện tử theo Nghị định 123/2020/NĐ-CP & TT 78/2021/TT-BTC)',
    notes: [
      '1. Hóa đơn điện tử có mã của cơ quan thuế được tra cứu trực tiếp tại cổng thông tin điện tử',
      '2. Hình thức thanh toán: Chuyển khoản ngân hàng / Tiền mặt',
    ],
    signLeft: 'Người mua hàng',
    signRight: 'Người bán hàng',
    defaultSize: 'A4',
    defaultOrientation: 'portrait',
    defaultEmptyRows: 4,
    signatureStyle: 'two_blocks',
    showVietQR: true,
    showBarcode: true,
    showDocQr: true,
    showBankInfo: true,
    showLogo: true,
    codePlacement: 'header',
  },
  quote: {
    title: 'BẢNG BÁO GIÁ THIẾT BỊ & DỊCH VỤ',
    subtitle: 'Bảng báo giá có hiệu lực trong vòng 15 ngày kể từ ngày lập',
    notes: [
      '1. Báo giá có giá trị trong vòng 15 ngày kể từ ngày phát hành',
      '2. Giá trên chưa bao gồm thuế VAT (nếu có) và phí vận chuyển ngoài phạm vi hỗ trợ',
      '3. Phương thức thanh toán: Chuyển khoản hoặc Tiền mặt khi xác nhận đặt hàng',
      '4. Hàng hóa được bảo hành chính hãng theo tiêu chuẩn của nhà sản xuất',
    ],
    signLeft: 'Khách hàng xác nhận',
    signRight: 'Người lập báo giá',
    defaultSize: 'A4',
    defaultOrientation: 'portrait',
    defaultEmptyRows: 4,
    signatureStyle: 'two_blocks',
    showVietQR: true,
    showBarcode: true,
    showDocQr: true,
    showBankInfo: true,
    showLogo: true,
    codePlacement: 'header',
  },
  asset_handover: {
    title: 'BIÊN BẢN BÀN GIAO & CUNG CẤP TÀI SẢN',
    subtitle: '',
    notes: [
      '1. Tài sản được bàn giao mới 100%, hoạt động ổn định và đầy đủ phụ kiện kèm theo',
      '2. Cán bộ tiếp nhận có trách nhiệm bảo quản, sử dụng đúng mục đích theo quy định',
      '3. Mọi sự cố hoặc hư hỏng phải báo cáo ngay cho bộ phận quản lý tài sản',
    ],
    signLeft: 'Người nhận bàn giao (Cán bộ sử dụng)',
    signRight: 'Người bàn giao (Quản lý thiết bị)',
    defaultSize: 'A4',
    defaultOrientation: 'portrait',
    defaultEmptyRows: 4,
    signatureStyle: 'two_blocks',
    showVietQR: false,
    showBarcode: true,
    showDocQr: true,
    showBankInfo: false,
    showLogo: true,
    codePlacement: 'header',
  },
  asset_transfer: {
    title: 'PHIẾU ĐIỀU CHUYỂN TÀI SẢN & KHO NỘI BỘ',
    subtitle: '',
    notes: [
      '1. Điều chuyển tài sản theo kế hoạch và điều phối nội bộ của ban quản lý',
      '2. Bên giao và bên nhận chịu trách nhiệm kiểm đếm số lượng và chất lượng thực tế',
    ],
    signLeft: 'Thủ kho tiếp nhận (Kho nhận)',
    signRight: 'Thủ kho xuất điều chuyển (Kho xuất)',
    defaultSize: 'A4',
    defaultOrientation: 'portrait',
    defaultEmptyRows: 4,
    signatureStyle: 'two_blocks',
    showVietQR: false,
    showBarcode: true,
    showDocQr: true,
    showBankInfo: false,
    showLogo: true,
    codePlacement: 'header',
  },
  stock_disposal: {
    title: 'BIÊN BẢN KIỂM KÊ & TIÊU HỦY VẬT TƯ, TÀI SẢN',
    subtitle: '',
    notes: [
      '1. Hội đồng tiêu hủy đã thẩm định tài sản hư hỏng không còn khả năng phục hồi',
      '2. Quá trình tiêu hủy diễn ra theo đúng quy trình an toàn và quy định bảo vệ môi trường',
    ],
    signLeft: 'Trưởng ban / Hội đồng tiêu hủy',
    signRight: 'Đại diện bộ phận kỹ thuật & Kho',
    defaultSize: 'A4',
    defaultOrientation: 'portrait',
    defaultEmptyRows: 4,
    signatureStyle: 'two_blocks',
    showVietQR: false,
    showBarcode: true,
    showDocQr: true,
    showBankInfo: false,
    showLogo: true,
    codePlacement: 'header',
  },
  liquidation_receipt: {
    title: 'PHIẾU THU TIỀN THANH LÝ VẬT TƯ / TÀI SẢN',
    subtitle: '',
    notes: [
      '1. Thiết bị thanh lý bán theo nguyên trạng thực tế, không kèm cam kết bảo hành đổi trả',
      '2. Người mua đã kiểm tra trực tiếp và đồng ý thanh toán đủ 100% giá trị',
    ],
    signLeft: 'Khách mua thanh lý',
    signRight: 'Đại diện thanh lý / Kế toán',
    defaultSize: 'A4',
    defaultOrientation: 'portrait',
    defaultEmptyRows: 4,
    signatureStyle: 'two_blocks',
    showVietQR: true,
    showBarcode: true,
    showDocQr: true,
    showBankInfo: true,
    showLogo: true,
    codePlacement: 'header',
  },
  delivery_dispatch: {
    title: 'PHIẾU ĐIỀU PHỐI GIAO HÀNG & THU TIỀN COD',
    subtitle: '',
    notes: [
      '1. Nhân viên giao hàng / đối tác vận chuyển có trách nhiệm bảo quản nguyên vẹn kiện hàng',
      '2. Thu đúng số tiền COD ghi trên phiếu và nộp lại đầy đủ cho thu ngân trong ngày',
    ],
    signLeft: 'Nhân viên giao nhận / Tài xế',
    signRight: 'Điều phối viên xuất hàng',
    defaultSize: 'A5',
    defaultOrientation: 'portrait',
    defaultEmptyRows: 2,
    signatureStyle: 'two_blocks',
    showVietQR: true,
    showBarcode: true,
    showDocQr: true,
    showBankInfo: true,
    showLogo: true,
    codePlacement: 'header',
  },
  shipping_label: {
    title: 'TEM VẬN ĐƠN DÁN KIỆN HÀNG',
    subtitle: '',
    notes: [
      '1. Hàng điện tử dễ vỡ - Xin vui lòng nhẹ tay!',
      '2. Kiểm tra đúng tên người nhận và số điện thoại trước khi giao hàng',
    ],
    signLeft: 'Người nhận',
    signRight: 'Người gửi',
    defaultSize: 'K80',
    defaultOrientation: 'portrait',
    defaultEmptyRows: 0,
    signatureStyle: 'two_blocks',
    showVietQR: true,
    showBarcode: true,
    showDocQr: true,
    showBankInfo: true,
    showLogo: true,
    codePlacement: 'header',
  },
  goods_delivery_record: {
    title: 'BIÊN BẢN GIAO NHẬN HÀNG HÓA',
    subtitle: '',
    notes: [
      '1. Hàng hóa được giao nhận mới 100%, đầy đủ phụ kiện (adapter) kèm theo.',
      '2. Hình thức thanh toán: Tiền Mặt / Chuyển Khoản / Thanh toán cho người giao hàng.',
      '3. Bên Mua (bên B) kiểm tra hàng hóa trước khi nhận. Mọi sự thiếu sót về sau không được giải quyết.',
    ],
    signLeft: 'ĐẠI DIỆN BÊN MUA (BÊN B)',
    signRight: 'ĐẠI DIỆN BÊN BÁN (BÊN A)',
    defaultSize: 'A4',
    defaultOrientation: 'portrait',
    defaultEmptyRows: 4,
    signatureStyle: 'two_blocks',
    showVietQR: false,
    showBarcode: true,
    showDocQr: true,
    showBankInfo: false,
    showLogo: true,
    codePlacement: 'header',
  },
  sales_return: {
    title: 'HÀNG BÁN TRẢ LẠI',
    subtitle: 'Mẫu số 02 - TT (Ban hành theo TT số 200/2014/TT-BTC ngày 22/12/2014 của BTC)',
    notes: [
      '1. Số chứng từ gốc kèm theo hợp lệ',
      '2. Định khoản kế toán: Nợ 1561/5212 - Có 6321/1311',
    ],
    signLeft: 'Người giao hàng',
    signRight: 'Người lập phiếu',
    defaultSize: 'A4',
    defaultOrientation: 'portrait',
    defaultEmptyRows: 4,
    signatureStyle: 'five_blocks',
    showVietQR: false,
    showBarcode: true,
    showDocQr: true,
    showBankInfo: false,
    showLogo: true,
    codePlacement: 'header',
  },
  goods_handover_exchange: {
    title: 'BIÊN BẢN BÀN GIAO - TRAO ĐỔI HÀNG HÓA',
    subtitle: 'Quy trình thu cũ đổi mới & khấu hao linh kiện thiết bị (Theo Ảnh 1)',
    notes: [
      '1. Bên A xác nhận Bên B đã giao cho Bên A đúng chủng loại và đủ số lượng hàng như trên.',
      '2. Lưu ý: Xuất HĐ linh kiện thay thế cho đủ tiền chênh lệch.',
      '3. Hai bên đồng ý, thống nhất ký tên. Biên bản được lập thành 02 bản, mỗi bên giữ 01 bản có giá trị pháp lý như nhau.',
    ],
    signLeft: 'ĐẠI DIỆN BÊN A',
    signRight: 'ĐẠI DIỆN BÊN B',
    defaultSize: 'A4',
    defaultOrientation: 'portrait',
    defaultEmptyRows: 2,
    signatureStyle: 'two_blocks',
    showVietQR: false,
    showBarcode: true,
    showDocQr: true,
    showBankInfo: false,
    showLogo: true,
    codePlacement: 'header',
  },
  goods_return_invoice_recall: {
    title: 'BIÊN BẢN TRẢ HÀNG VÀ THU HỒI HOÁ ĐƠN',
    subtitle: 'Căn cứ Nghị định 123/2020/NĐ-CP & Thông tư 78/2021/TT-BTC (Theo Ảnh 2)',
    notes: [
      '1. Hai bên cam kết chịu trách nhiệm kê khai đúng theo quy định của pháp luật về quản lý và phát hành hoá đơn.',
      '2. Biên bản này được lập thành 02 (hai) bản có giá trị pháp lý như sau, bên mua giữ một bản, bên bán giữ một bản.',
    ],
    signLeft: 'ĐẠI DIỆN BÊN MUA\n(Ký tên, đóng dấu)',
    signRight: 'ĐẠI DIỆN BÊN BÁN\n(Ký tên, đóng dấu)',
    defaultSize: 'A4',
    defaultOrientation: 'portrait',
    defaultEmptyRows: 2,
    signatureStyle: 'two_blocks',
    showVietQR: false,
    showBarcode: true,
    showDocQr: true,
    showBankInfo: false,
    showLogo: true,
    codePlacement: 'header',
  },
  work_completion_handover: {
    title: 'BIÊN BẢN XÁC NHẬN HOÀN THÀNH CÔNG VIỆC',
    subtitle: 'Biên bản bàn giao và nghiệm thu dịch vụ sửa chữa / kỹ thuật (Theo Ảnh 3)',
    notes: [
      '1. Bên A bàn giao cho bên B như sau: Bên A sửa chữa máy in/máy tính và bàn giao máy trong tình trạng hoạt động tốt.',
      '2. Hai bên đồng ý nghiệm thu và xác nhận bàn giao đầy đủ.',
    ],
    signLeft: 'Đại diện bên A',
    signRight: 'Đại diện bên B',
    defaultSize: 'A4',
    defaultOrientation: 'portrait',
    defaultEmptyRows: 3,
    signatureStyle: 'two_blocks',
    showVietQR: false,
    showBarcode: true,
    showDocQr: true,
    showBankInfo: false,
    showLogo: true,
    codePlacement: 'header',
  },
  goods_exchange_invoice_replace: {
    title: 'BIÊN BẢN ĐỔI HÀNG VÀ THAY ĐỔI HOÁ ĐƠN',
    subtitle: 'Thỏa thuận đổi hàng hóa và xuất hóa đơn điều chỉnh/thay thế (Theo Ảnh 4)',
    notes: [
      '1. Hai bên cam kết chịu trách nhiệm kê khai đúng theo quy định của pháp luật về quản lý và phát hành hoá đơn.',
      '2. Biên bản này được lập thành 02 (hai) bản có giá trị pháp lý như sau, bên mua giữ một bản, bên bán giữ một bản.',
    ],
    signLeft: 'ĐẠI DIỆN BÊN MUA\n(Ký tên, đóng dấu)',
    signRight: 'ĐẠI DIỆN BÊN BÁN\n(Ký tên, đóng dấu)',
    defaultSize: 'A4',
    defaultOrientation: 'portrait',
    defaultEmptyRows: 2,
    signatureStyle: 'two_blocks',
    showVietQR: false,
    showBarcode: true,
    showDocQr: true,
    showBankInfo: false,
    showLogo: true,
    codePlacement: 'header',
  },
};

/**
 * Returns merged PrintDocConfig for a given docType with fallback to default template
 */
export function getEffectivePrintConfig(
  settings?: StoreSettings | null,
  docType: PrintDocType = 'sales_invoice'
): PrintDocConfig {
  const def = DEFAULT_DOC_TEMPLATES[docType] || DEFAULT_DOC_TEMPLATES.sales_invoice;
  const userConfig = settings?.printDocConfigs?.[docType];

  return {
    paperSize: userConfig?.paperSize || def.defaultSize,
    orientation: userConfig?.orientation || def.defaultOrientation,
    emptyRowsCount:
      userConfig?.emptyRowsCount !== undefined ? userConfig.emptyRowsCount : def.defaultEmptyRows,
    signatureStyle: userConfig?.signatureStyle || def.signatureStyle,
    showVietQR: userConfig?.showVietQR !== undefined ? userConfig.showVietQR : def.showVietQR,
    customTitle: userConfig?.customTitle !== undefined && userConfig.customTitle.trim() !== '' ? userConfig.customTitle : def.title,
    customSubtitle: userConfig?.customSubtitle !== undefined ? userConfig.customSubtitle : (def.subtitle || ''),
    notes: userConfig?.notes && userConfig.notes.length > 0 ? userConfig.notes : [...def.notes],
    showLogo: userConfig?.showLogo !== undefined ? userConfig.showLogo : def.showLogo,
    showBarcode: userConfig?.showBarcode !== undefined ? userConfig.showBarcode : def.showBarcode,
    showDocQr: userConfig?.showDocQr !== undefined ? userConfig.showDocQr : def.showDocQr,
    showBankInfo: userConfig?.showBankInfo !== undefined ? userConfig.showBankInfo : def.showBankInfo,
    codePlacement: userConfig?.codePlacement || def.codePlacement,
    signLeftLabel: userConfig?.signLeftLabel || def.signLeft,
    signRightLabel: userConfig?.signRightLabel || def.signRight,
    defaultWarehouse: userConfig?.defaultWarehouse || settings?.defaultWarehouse || 'Gia Phúc',
    defaultCreator: userConfig?.defaultCreator || settings?.defaultCreatorName || 'Mr. Thơm',
  };
}
